name: AccuKnox Container Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Run AccuKnox Container Scanner
        uses: Vickydew1/container-scan-action@main
        
        with:
          # Required
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}

          # Container image
          image_name: "nginx"
          tag: "latest"

          # Scan configuration
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

          # Behavior flags
          soft_fail: true
          keep_results: true

          # SBOM (optional)
          generate_sbom: true
          project_name: "Test1"
