name: Accuknox IAC scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  iac_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AccuKnox IaC Scan
        uses: accuknox/iac-scan-action@v1.0.2
        with:
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}

          # Optional inputs
          directory: "."      # default directory
          file: ""            # specific file, optional
          compact: true       # hide code blocks in output
          quiet: true         # show only failed checks
          soft_fail: true    # fail workflow on scan failures
          framework: ""       # specify terraform/k8s if needed
